Update tags for 2025.1
carminevassallo/official-images pull request #2
Opened 2024-11-05 16:38 UTC by carminevassallo

2024-11-08 13:53 UTC, vilchik-elena commented
@carminevassallo would not that be better if this PR is based on https://github.com/carminevassallo/official-images/pull/1?

2024-11-08 14:00 UTC, vilchik-elena requested changes

2024-11-08 14:00 UTC, vilchik-elena commented on library/sonarqube
> +Tags: 2025.1.1-lta-developer, 2025.1-lta-developer, 2025-lta-developer
why `2025.1.1`? it should be `2025.1.0` as far as I understand

2024-11-08 14:00 UTC, vilchik-elena commented on library/sonarqube
>  Directory: 9/developer
we probably will change the directory

2024-11-08 14:00 UTC, vilchik-elena commented on library/sonarqube
>  Directory: 10/community
`community-build`?

2024-11-08 14:00 UTC, vilchik-elena commented on library/sonarqube
> +Tags: 2025.1.1-enterprise, 2025.1-enterprise, 2025-enterprise, enterprise
didn't we say that `2025-...` does not make sense?

2024-11-28 15:37 UTC, carminevassallo commented on library/sonarqube
> +Tags: 2025.1.1-lta-developer, 2025.1-lta-developer, 2025-lta-developer
indeed fixing this

2025-01-20 15:38 UTC, closed without merging